### PR TITLE
Fix/symbol observable (again)

### LINKED ISSUE #245: toObservable() is not compatible with Rx (observer is not partial)
**IxJS version:**

**Code to reproduce:**
```ts
import {from} from 'rxjs'
import {AsyncIterableX, toObservable} from 'ix/asynciterable'

from(toObservable(AsyncIterableX.from([1,2,3])))
```

**Expected behavior:**
Should compile

**Actual behavior:**
Fails with
```
[ts]
Type 'Observable<T>' is not assignable to type 'Subscribable<T>'.
  Types of property 'subscribe' are incompatible.
    Type '(observer: Observer<T>) => Subscription' is not assignable to type '{ (observer?: NextObserver<T> | ErrorObserver<T> | CompletionObserver<T> | undefined): Unsubscribable; (next?: ((value: T) => void) | undefined, error?: ((error: any) => void) | undefined, complete?: (() => void) | undefined): Unsubscribable; }'.
      Types of parameters 'observer' and 'next' are incompatible.
        Type '((value: T) => void) | undefined' is not assignable to type 'Observer<T>'.
```
This is because `Observable` as defined in Ix takes an Observer where all of `next`, `error` and `complete` _have_ to be provided, instead of being optional.

**Additional information:**

### PR DESCRIPTION
**Pull request by trxcllnt**
Fixes #245 again.

* Copied the symbol-observable handling from rxjs@6x, which lets us move rxjs@5.5.11 back to a dev-dependency.
* Added a test for `AsyncIterable.from()` accepting an rxjs Observable as well (thanks @arseneyr!). 

@felixfbecker does this look right to you?

### CODE REVIEW

**Comment by felixfbecker** [comment]
> which lets us move rxjs@5.5.11 back to a dev-dependency.

🙇 Everyone already using rxjs 6 says thank you!

File: spec/Ix.ts [hunk 1]
```diff
@@ -1,7 +1,9 @@
 /* tslint:disable */
-
 (<any>global).window = (<any>global).window || global;
 
+// Require rxjs first so we pick up its polyfilled Symbol.observable
```
Comment (felixfbecker) [inline spec/Ix.ts]: Just for the record, this line can go away once we upgrade to Rx 6, correct?

File: spec/asynciterable-operators/toobservable-spec.ts [hunk 2]
```diff
@@ -1,11 +1,11 @@
 import * as Ix from '../Ix';
+const { symbolObservable } = (Ix as any).default;
```
Comment (felixfbecker) [inline spec/asynciterable-operators/toobservable-spec.ts]: Why does this have to be imported like this with a cast to `any`?

File: spec/Ix.ts (hunk 1 above)
Comment (trxcllnt) [reply spec/Ix.ts]: Yes

File: src/observer.ts [hunk 3]
```diff
@@ -1,35 +1,25 @@
...
-  if (typeof Symbol['observable'] === 'undefined') {
-    (Symbol as any)['observable'] = symbolObservable;
-  } else {
-    symbolObservable = Symbol['observable'];
-  }
-}
-export { symbolObservable };
+// Symbol.observable or a string "@@observable". Used for interop.
+// Referenced via string indexer so closure-compiler doesn't mangle.
+export const observable = (typeof Symbol === 'function' && Symbol.observable) || '@@observable';
```
Comment (felixfbecker) [inline src/observer.ts]: `observable` seems like a weird name in the context of this file, I would name this `symbolObservable`. Or put it into its own file `symbol.ts`.

File: src/observer.ts [hunk 4]
```diff
@@ -82,10 +72,10 @@ export interface Observer<T> {
 }
 
 export interface Observable<T> {
```
Comment (felixfbecker) [inline src/observer.ts]: Can we verify somehow that
1. an Rx `Observable` can be passed to Ix `from()`
2. the `Observable` returned by `toObservable` can be passed to Rx methods (at the very least `from()`)

Comment (trxcllnt) [reply src/observer.ts]: you mean like these tests here? https://github.com/ReactiveX/IxJS/blob/ead5b475bde5e242cdaf834ed9486c20fe003876/spec/asynciterable-operators/toobservable-spec.ts#L132

File: spec/asynciterable-operators/toobservable-spec.ts (hunk 2 above)
Comment (trxcllnt) [reply spec/asynciterable-operators/toobservable-spec.ts]: I mean Typescript. We use Terser for the es2015+ umd bundles, but closure for the es5 umd. Even with all its warts it's still the best option at the moment, because its compiled iterators are as fast (or sometimes faster, in the case of FF/Edge) as native iterators in es2015+ envs.
